import { Component, OnInit, ViewChild, ViewEncapsulation, ElementRef } from '@angular/core';

import * as d3 from 'd3';
import * as d3Chromatic from 'd3-scale-chromatic';

// Data Service
// import { GetDataService } from '../_services/get-data.service';

@Component({
  selector: 'app-distrib-plot',
  templateUrl: './distrib-plot.component.html',
  styleUrls: ['./distrib-plot.component.scss'],
  encapsulation: ViewEncapsulation.Native
})

export class DistribPlotComponent implements OnInit {
  @ViewChild('chart') private chartContainer: ElementRef;

  df: Array<Object>;
  test: any;


  // df: Array<Object> = [
  //   { 'sample_id': 'TUL5', 'avg': 22.4791, 'indivs': [31.06754, 18.08720, 18.28256], 'row': "E", 'cols': [1, 2, 3] },
  //   { 'sample_id': 'TUL23', 'avg': 54.80144, 'indivs': [49.96560, 57.62928, 56.80943], 'row': "G", 'cols': [7, 8, 9] },
  //   { 'sample_id': 'TUL3', 'avg': 8.75909, 'indivs': [9.07368, 8.61540, 8.58819], 'row': "C", 'cols': [1, 2, 3] }
  // ]
  //
  //
  df2: Array<Object> =
    [
      {
        "filename": "Specimen_001_A1_A01_001.fcs",
        "MFI_all": 60.4,
        "pct_fluor": 0.43,
        "MFI": 1993,
        "plate": 1,
        "well": "A1",
        "row": "A",
        "col": 1,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 1",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.085699,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 5.7291666667,
        "sample_mean": 0.106549,
        "sample_std": 0.0210195023,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_A2_A02_002.fcs",
        "MFI_all": 57.5,
        "pct_fluor": 0.61,
        "MFI": 2094,
        "plate": 1,
        "well": "A2",
        "row": "A",
        "col": 2,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 1",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.127734,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 15.625,
        "sample_mean": 0.106549,
        "sample_std": 0.0210195023,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_A3_A03_003.fcs",
        "MFI_all": 59.6,
        "pct_fluor": 0.46,
        "MFI": 2309,
        "plate": 1,
        "well": "A3",
        "row": "A",
        "col": 3,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 1",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.106214,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 9.8958333333,
        "sample_mean": 0.106549,
        "sample_std": 0.0210195023,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_A4_A04_004.fcs",
        "MFI_all": 1789,
        "pct_fluor": 90.6,
        "MFI": 2077,
        "plate": 1,
        "well": "A4",
        "row": "A",
        "col": 4,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 9",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 18.81762,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 80.2083333333,
        "sample_mean": 17.5283,
        "sample_std": 1.2232905007,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_A5_A05_005.fcs",
        "MFI_all": 1654,
        "pct_fluor": 88.6,
        "MFI": 1962,
        "plate": 1,
        "well": "A5",
        "row": "A",
        "col": 5,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 9",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 17.38332,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 79.1666666667,
        "sample_mean": 17.5283,
        "sample_std": 1.2232905007,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_A6_A06_006.fcs",
        "MFI_all": 1540,
        "pct_fluor": 85.2,
        "MFI": 1923,
        "plate": 1,
        "well": "A6",
        "row": "A",
        "col": 6,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 9",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 16.38396,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 78.125,
        "sample_mean": 17.5283,
        "sample_std": 1.2232905007,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_A7_A07_007.fcs",
        "MFI_all": 117,
        "pct_fluor": 1.86,
        "MFI": 1369,
        "plate": 1,
        "well": "A7",
        "row": "A",
        "col": 7,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 17",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.254634,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 38.5416666667,
        "sample_mean": 0.2039643333,
        "sample_std": 0.0441300245,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_A8_A08_008.fcs",
        "MFI_all": 111,
        "pct_fluor": 1.47,
        "MFI": 1247,
        "plate": 1,
        "well": "A8",
        "row": "A",
        "col": 8,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 17",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.183309,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 28.125,
        "sample_mean": 0.2039643333,
        "sample_std": 0.0441300245,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_A9_A09_009.fcs",
        "MFI_all": 113,
        "pct_fluor": 1.42,
        "MFI": 1225,
        "plate": 1,
        "well": "A9",
        "row": "A",
        "col": 9,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 17",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.17395,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 25.5208333333,
        "sample_mean": 0.2039643333,
        "sample_std": 0.0441300245,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_A10_A10_010.fcs",
        "MFI_all": 277,
        "pct_fluor": 16,
        "MFI": 736,
        "plate": 1,
        "well": "A10",
        "row": "A",
        "col": 10,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 25",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 1.1776,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 56.7708333333,
        "sample_mean": 1.1555666667,
        "sample_std": 0.1160790715,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_A11_A11_011.fcs",
        "MFI_all": 287,
        "pct_fluor": 16.9,
        "MFI": 745,
        "plate": 1,
        "well": "A11",
        "row": "A",
        "col": 11,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 25",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 1.25905,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 58.3333333333,
        "sample_mean": 1.1555666667,
        "sample_std": 0.1160790715,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_A12_A12_012.fcs",
        "MFI_all": 253,
        "pct_fluor": 13.5,
        "MFI": 763,
        "plate": 1,
        "well": "A12",
        "row": "A",
        "col": 12,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 25",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 1.03005,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 54.1666666667,
        "sample_mean": 1.1555666667,
        "sample_std": 0.1160790715,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_B1_B01_013.fcs",
        "MFI_all": 96,
        "pct_fluor": 1.02,
        "MFI": 815,
        "plate": 1,
        "well": "B1",
        "row": "B",
        "col": 1,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 2",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.08313,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 4.6875,
        "sample_mean": 0.0950673333,
        "sample_std": 0.0146046158,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_B2_B02_014.fcs",
        "MFI_all": 97.6,
        "pct_fluor": 1.24,
        "MFI": 898,
        "plate": 1,
        "well": "B2",
        "row": "B",
        "col": 2,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 2",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.111352,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 10.9375,
        "sample_mean": 0.0950673333,
        "sample_std": 0.0146046158,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_B3_B03_015.fcs",
        "MFI_all": 101,
        "pct_fluor": 1.08,
        "MFI": 840,
        "plate": 1,
        "well": "B3",
        "row": "B",
        "col": 3,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 2",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.09072,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 7.2916666667,
        "sample_mean": 0.0950673333,
        "sample_std": 0.0146046158,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_B4_B04_016.fcs",
        "MFI_all": 1260,
        "pct_fluor": 83.5,
        "MFI": 1574,
        "plate": 1,
        "well": "B4",
        "row": "B",
        "col": 4,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 10",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 13.1429,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 75,
        "sample_mean": 14.0355866667,
        "sample_std": 0.8877911773,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_B5_B05_017.fcs",
        "MFI_all": 1361,
        "pct_fluor": 85.8,
        "MFI": 1637,
        "plate": 1,
        "well": "B5",
        "row": "B",
        "col": 5,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 10",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 14.04546,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 76.0416666667,
        "sample_mean": 14.0355866667,
        "sample_std": 0.8877911773,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_B6_B06_018.fcs",
        "MFI_all": 1447,
        "pct_fluor": 88.8,
        "MFI": 1680,
        "plate": 1,
        "well": "B6",
        "row": "B",
        "col": 6,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 10",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 14.9184,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 77.6041666667,
        "sample_mean": 14.0355866667,
        "sample_std": 0.8877911773,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_B7_B07_019.fcs",
        "MFI_all": 95.8,
        "pct_fluor": 1.24,
        "MFI": 1030,
        "plate": 1,
        "well": "B7",
        "row": "B",
        "col": 7,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 18",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.12772,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 15.1041666667,
        "sample_mean": 0.0912053333,
        "sample_std": 0.0324081336,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_B8_B08_020.fcs",
        "MFI_all": 91.1,
        "pct_fluor": 0.92,
        "MFI": 870,
        "plate": 1,
        "well": "B8",
        "row": "B",
        "col": 8,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 18",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.08004,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 3.125,
        "sample_mean": 0.0912053333,
        "sample_std": 0.0324081336,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_B9_B09_021.fcs",
        "MFI_all": 87.6,
        "pct_fluor": 0.64,
        "MFI": 1029,
        "plate": 1,
        "well": "B9",
        "row": "B",
        "col": 9,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 18",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.065856,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 2.0833333333,
        "sample_mean": 0.0912053333,
        "sample_std": 0.0324081336,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_B10_B10_022.fcs",
        "MFI_all": 1417,
        "pct_fluor": 90.1,
        "MFI": 1613,
        "plate": 1,
        "well": "B10",
        "row": "B",
        "col": 10,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 26",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 14.53313,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 76.5625,
        "sample_mean": 14.1676566667,
        "sample_std": 0.9414772915,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_B11_B11_023.fcs",
        "MFI_all": 1463,
        "pct_fluor": 91.8,
        "MFI": 1620,
        "plate": 1,
        "well": "B11",
        "row": "B",
        "col": 11,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 26",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 14.8716,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 77.0833333333,
        "sample_mean": 14.1676566667,
        "sample_std": 0.9414772915,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_B12_B12_024.fcs",
        "MFI_all": 1290,
        "pct_fluor": 86.4,
        "MFI": 1516,
        "plate": 1,
        "well": "B12",
        "row": "B",
        "col": 12,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 26",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 13.09824,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 74.4791666667,
        "sample_mean": 14.1676566667,
        "sample_std": 0.9414772915,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_C1_C01_025.fcs",
        "MFI_all": 56.3,
        "pct_fluor": 1.22,
        "MFI": 1365,
        "plate": 1,
        "well": "C1",
        "row": "C",
        "col": 1,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 3",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.16653,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 23.9583333333,
        "sample_mean": 0.158078,
        "sample_std": 0.0268932726,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_C2_C02_026.fcs",
        "MFI_all": 46.1,
        "pct_fluor": 0.66,
        "MFI": 1939,
        "plate": 1,
        "well": "C2",
        "row": "C",
        "col": 2,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 3",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.127974,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 16.1458333333,
        "sample_mean": 0.158078,
        "sample_std": 0.0268932726,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_C3_C03_027.fcs",
        "MFI_all": 50.3,
        "pct_fluor": 0.9,
        "MFI": 1997,
        "plate": 1,
        "well": "C3",
        "row": "C",
        "col": 3,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 3",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.17973,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 26.5625,
        "sample_mean": 0.158078,
        "sample_std": 0.0268932726,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_C4_C04_028.fcs",
        "MFI_all": 514,
        "pct_fluor": 43.4,
        "MFI": 933,
        "plate": 1,
        "well": "C4",
        "row": "C",
        "col": 4,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 11",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 4.04922,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 61.4583333333,
        "sample_mean": 4.4464466667,
        "sample_std": 0.5270353754,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_C5_C05_029.fcs",
        "MFI_all": 532,
        "pct_fluor": 46.2,
        "MFI": 919,
        "plate": 1,
        "well": "C5",
        "row": "C",
        "col": 5,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 11",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 4.24578,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 61.9791666667,
        "sample_mean": 4.4464466667,
        "sample_std": 0.5270353754,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_C6_C06_030.fcs",
        "MFI_all": 606,
        "pct_fluor": 52.6,
        "MFI": 959,
        "plate": 1,
        "well": "C6",
        "row": "C",
        "col": 6,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 11",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 5.04434,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 63.5416666667,
        "sample_mean": 4.4464466667,
        "sample_std": 0.5270353754,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_C7_C07_031.fcs",
        "MFI_all": 17575,
        "pct_fluor": 98.1,
        "MFI": 19058,
        "plate": 1,
        "well": "C7",
        "row": "C",
        "col": 7,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 19",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 186.95898,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 97.3958333333,
        "sample_mean": 180.69233,
        "sample_std": 16.6270525686,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_C8_C08_032.fcs",
        "MFI_all": 8380,
        "pct_fluor": 81.9,
        "MFI": 19761,
        "plate": 1,
        "well": "C8",
        "row": "C",
        "col": 8,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 19",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 161.84259,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 95.3125,
        "sample_mean": 180.69233,
        "sample_std": 16.6270525686,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_C9_C09_033.fcs",
        "MFI_all": 16840,
        "pct_fluor": 96.2,
        "MFI": 20091,
        "plate": 1,
        "well": "C9",
        "row": "C",
        "col": 9,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 19",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 193.27542,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 98.9583333333,
        "sample_mean": 180.69233,
        "sample_std": 16.6270525686,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_C10_C10_034.fcs",
        "MFI_all": 1184,
        "pct_fluor": 80.9,
        "MFI": 1510,
        "plate": 1,
        "well": "C10",
        "row": "C",
        "col": 10,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 27",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 12.2159,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 73.4375,
        "sample_mean": 11.9454566667,
        "sample_std": 0.4660852804,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_C11_C11_035.fcs",
        "MFI_all": 1114,
        "pct_fluor": 74.9,
        "MFI": 1523,
        "plate": 1,
        "well": "C11",
        "row": "C",
        "col": 11,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 27",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 11.40727,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 71.875,
        "sample_mean": 11.9454566667,
        "sample_std": 0.4660852804,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_C12_C12_036.fcs",
        "MFI_all": 1175,
        "pct_fluor": 76,
        "MFI": 1607,
        "plate": 1,
        "well": "C12",
        "row": "C",
        "col": 12,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 27",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 12.2132,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 72.9166666667,
        "sample_mean": 11.9454566667,
        "sample_std": 0.4660852804,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_D1_D01_037.fcs",
        "MFI_all": 763,
        "pct_fluor": 64.4,
        "MFI": 1094,
        "plate": 1,
        "well": "D1",
        "row": "D",
        "col": 1,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 4",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 7.04536,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 67.1875,
        "sample_mean": 7.6761466667,
        "sample_std": 0.6666248628,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_D2_D02_038.fcs",
        "MFI_all": 811,
        "pct_fluor": 67.7,
        "MFI": 1124,
        "plate": 1,
        "well": "D2",
        "row": "D",
        "col": 2,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 4",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 7.60948,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 68.75,
        "sample_mean": 7.6761466667,
        "sample_std": 0.6666248628,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_D3_D03_039.fcs",
        "MFI_all": 874,
        "pct_fluor": 72,
        "MFI": 1163,
        "plate": 1,
        "well": "D3",
        "row": "D",
        "col": 3,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 4",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 8.3736,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 70.3125,
        "sample_mean": 7.6761466667,
        "sample_std": 0.6666248628,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_D4_D04_040.fcs",
        "MFI_all": 258,
        "pct_fluor": 12.4,
        "MFI": 849,
        "plate": 1,
        "well": "D4",
        "row": "D",
        "col": 4,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 12",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 1.05276,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 55.2083333333,
        "sample_mean": 1.1491866667,
        "sample_std": 0.092636853,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_D5_D05_041.fcs",
        "MFI_all": 273,
        "pct_fluor": 14.2,
        "MFI": 815,
        "plate": 1,
        "well": "D5",
        "row": "D",
        "col": 5,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 12",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 1.1573,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 56.25,
        "sample_mean": 1.1491866667,
        "sample_std": 0.092636853,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_D6_D06_042.fcs",
        "MFI_all": 286,
        "pct_fluor": 15,
        "MFI": 825,
        "plate": 1,
        "well": "D6",
        "row": "D",
        "col": 6,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 12",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 1.2375,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 57.8125,
        "sample_mean": 1.1491866667,
        "sample_std": 0.092636853,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_D7_D07_043.fcs",
        "MFI_all": 17918,
        "pct_fluor": 98.8,
        "MFI": 18888,
        "plate": 1,
        "well": "D7",
        "row": "D",
        "col": 7,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 20",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 186.61344,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 96.875,
        "sample_mean": 186.2660466667,
        "sample_std": 5.1969654279,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_D8_D08_044.fcs",
        "MFI_all": 15778,
        "pct_fluor": 96.2,
        "MFI": 18805,
        "plate": 1,
        "well": "D8",
        "row": "D",
        "col": 8,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 20",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 180.9041,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 96.3541666667,
        "sample_mean": 186.2660466667,
        "sample_std": 5.1969654279,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_D9_D09_045.fcs",
        "MFI_all": 15187,
        "pct_fluor": 94,
        "MFI": 20349,
        "plate": 1,
        "well": "D9",
        "row": "D",
        "col": 9,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 20",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 191.2806,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 98.4375,
        "sample_mean": 186.2660466667,
        "sample_std": 5.1969654279,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_D10_D10_046.fcs",
        "MFI_all": 640,
        "pct_fluor": 53.5,
        "MFI": 1013,
        "plate": 1,
        "well": "D10",
        "row": "D",
        "col": 10,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 28",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 5.41955,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 64.5833333333,
        "sample_mean": 5.3731933333,
        "sample_std": 1.9646252242,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_D11_D11_047.fcs",
        "MFI_all": 790,
        "pct_fluor": 64.9,
        "MFI": 1127,
        "plate": 1,
        "well": "D11",
        "row": "D",
        "col": 11,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 28",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 7.31423,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 68.2291666667,
        "sample_mean": 5.3731933333,
        "sample_std": 1.9646252242,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_D12_D12_048.fcs",
        "MFI_all": 475,
        "pct_fluor": 34.2,
        "MFI": 990,
        "plate": 1,
        "well": "D12",
        "row": "D",
        "col": 12,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 28",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 3.3858,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 59.8958333333,
        "sample_mean": 5.3731933333,
        "sample_std": 1.9646252242,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_E1_E01_049.fcs",
        "MFI_all": 72.7,
        "pct_fluor": 0.79,
        "MFI": 1512,
        "plate": 1,
        "well": "E1",
        "row": "E",
        "col": 1,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 5",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.119448,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 14.0625,
        "sample_mean": 0.1049366667,
        "sample_std": 0.0174309018,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_E2_E02_050.fcs",
        "MFI_all": 66,
        "pct_fluor": 0.64,
        "MFI": 1715,
        "plate": 1,
        "well": "E2",
        "row": "E",
        "col": 2,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 5",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.10976,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 10.4166666667,
        "sample_mean": 0.1049366667,
        "sample_std": 0.0174309018,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_E3_E03_051.fcs",
        "MFI_all": 72.8,
        "pct_fluor": 0.66,
        "MFI": 1297,
        "plate": 1,
        "well": "E3",
        "row": "E",
        "col": 3,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 5",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.085602,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 5.2083333333,
        "sample_mean": 0.1049366667,
        "sample_std": 0.0174309018,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_E4_E04_052.fcs",
        "MFI_all": 1169,
        "pct_fluor": 79.6,
        "MFI": 1520,
        "plate": 1,
        "well": "E4",
        "row": "E",
        "col": 4,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 13",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 12.0992,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 72.3958333333,
        "sample_mean": 12.5704933333,
        "sample_std": 0.6231349726,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_E5_E05_053.fcs",
        "MFI_all": 1211,
        "pct_fluor": 82.4,
        "MFI": 1497,
        "plate": 1,
        "well": "E5",
        "row": "E",
        "col": 5,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 13",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 12.33528,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 73.9583333333,
        "sample_mean": 12.5704933333,
        "sample_std": 0.6231349726,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_E6_E06_054.fcs",
        "MFI_all": 1292,
        "pct_fluor": 85,
        "MFI": 1562,
        "plate": 1,
        "well": "E6",
        "row": "E",
        "col": 6,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 13",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 13.277,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 75.5208333333,
        "sample_mean": 12.5704933333,
        "sample_std": 0.6231349726,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_E7_E07_055.fcs",
        "MFI_all": 5860,
        "pct_fluor": 96.9,
        "MFI": 6493,
        "plate": 1,
        "well": "E7",
        "row": "E",
        "col": 7,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 21",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 62.91717,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 89.0625,
        "sample_mean": 65.6011633333,
        "sample_std": 4.7341024316,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_E8_E08_056.fcs",
        "MFI_all": 5831,
        "pct_fluor": 96.6,
        "MFI": 6503,
        "plate": 1,
        "well": "E8",
        "row": "E",
        "col": 8,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 21",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 62.81898,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 88.5416666667,
        "sample_mean": 65.6011633333,
        "sample_std": 4.7341024316,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_E9_E09_057.fcs",
        "MFI_all": 6806,
        "pct_fluor": 98.2,
        "MFI": 7237,
        "plate": 1,
        "well": "E9",
        "row": "E",
        "col": 9,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 21",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 71.06734,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 90.1041666667,
        "sample_mean": 65.6011633333,
        "sample_std": 4.7341024316,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_E10_E10_058.fcs",
        "MFI_all": 3174,
        "pct_fluor": 96.9,
        "MFI": 3398,
        "plate": 1,
        "well": "E10",
        "row": "E",
        "col": 10,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 29",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 32.92662,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 84.8958333333,
        "sample_mean": 34.91789,
        "sample_std": 1.7976993413,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_E11_E11_059.fcs",
        "MFI_all": 3473,
        "pct_fluor": 96.2,
        "MFI": 3786,
        "plate": 1,
        "well": "E11",
        "row": "E",
        "col": 11,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 29",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 36.42132,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 86.9791666667,
        "sample_mean": 34.91789,
        "sample_std": 1.7976993413,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_E12_E12_060.fcs",
        "MFI_all": 3325,
        "pct_fluor": 95.1,
        "MFI": 3723,
        "plate": 1,
        "well": "E12",
        "row": "E",
        "col": 12,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 29",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 35.40573,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 86.4583333333,
        "sample_mean": 34.91789,
        "sample_std": 1.7976993413,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_F1_F01_061.fcs",
        "MFI_all": 848,
        "pct_fluor": 70.5,
        "MFI": 1142,
        "plate": 1,
        "well": "F1",
        "row": "F",
        "col": 1,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 6",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 8.0511,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 69.2708333333,
        "sample_mean": 8.8955733333,
        "sample_std": 1.3220693193,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_F2_F02_062.fcs",
        "MFI_all": 865,
        "pct_fluor": 73.1,
        "MFI": 1124,
        "plate": 1,
        "well": "F2",
        "row": "F",
        "col": 2,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 6",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 8.21644,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 69.7916666667,
        "sample_mean": 8.8955733333,
        "sample_std": 1.3220693193,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_F3_F03_063.fcs",
        "MFI_all": 1053,
        "pct_fluor": 82.3,
        "MFI": 1266,
        "plate": 1,
        "well": "F3",
        "row": "F",
        "col": 3,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 6",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 10.41918,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 71.3541666667,
        "sample_mean": 8.8955733333,
        "sample_std": 1.3220693193,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_F4_F04_064.fcs",
        "MFI_all": 1887,
        "pct_fluor": 94.3,
        "MFI": 2057,
        "plate": 1,
        "well": "F4",
        "row": "F",
        "col": 4,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 14",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 19.39751,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 80.7291666667,
        "sample_mean": 19.7643466667,
        "sample_std": 0.5813889165,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_F5_F05_065.fcs",
        "MFI_all": 1895,
        "pct_fluor": 94.7,
        "MFI": 2055,
        "plate": 1,
        "well": "F5",
        "row": "F",
        "col": 5,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 14",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 19.46085,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 81.25,
        "sample_mean": 19.7643466667,
        "sample_std": 0.5813889165,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_F6_F06_066.fcs",
        "MFI_all": 1985,
        "pct_fluor": 95.4,
        "MFI": 2142,
        "plate": 1,
        "well": "F6",
        "row": "F",
        "col": 6,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 14",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 20.43468,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 82.2916666667,
        "sample_mean": 19.7643466667,
        "sample_std": 0.5813889165,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_F7_F07_067.fcs",
        "MFI_all": 5839,
        "pct_fluor": 94.3,
        "MFI": 7097,
        "plate": 1,
        "well": "F7",
        "row": "F",
        "col": 7,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 22",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 66.92471,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 89.5833333333,
        "sample_mean": 76.5500633333,
        "sample_std": 8.4350967455,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_F8_F08_068.fcs",
        "MFI_all": 7726,
        "pct_fluor": 98.2,
        "MFI": 8154,
        "plate": 1,
        "well": "F8",
        "row": "F",
        "col": 8,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 22",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 80.07228,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 91.1458333333,
        "sample_mean": 76.5500633333,
        "sample_std": 8.4350967455,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_F9_F09_069.fcs",
        "MFI_all": 7896,
        "pct_fluor": 98,
        "MFI": 8434,
        "plate": 1,
        "well": "F9",
        "row": "F",
        "col": 9,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 22",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 82.6532,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 91.6666666667,
        "sample_mean": 76.5500633333,
        "sample_std": 8.4350967455,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_F10_F10_070.fcs",
        "MFI_all": 23921,
        "pct_fluor": 98.1,
        "MFI": 26285,
        "plate": 1,
        "well": "F10",
        "row": "F",
        "col": 10,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "Cr+",
        "sample_type": "positive control",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 257.85585,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 99.4791666667,
        "sample_mean": 180.97593,
        "sample_std": 69.6059660263,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_F11_F11_071.fcs",
        "MFI_all": 15260,
        "pct_fluor": 98.1,
        "MFI": 16599,
        "plate": 1,
        "well": "F11",
        "row": "F",
        "col": 11,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "Cr+",
        "sample_type": "positive control",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 162.83619,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 95.8333333333,
        "sample_mean": 180.97593,
        "sample_std": 69.6059660263,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_F12_F12_072.fcs",
        "MFI_all": 12071,
        "pct_fluor": 99.5,
        "MFI": 12285,
        "plate": 1,
        "well": "F12",
        "row": "F",
        "col": 12,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "Cr+",
        "sample_type": "positive control",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 122.23575,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 93.75,
        "sample_mean": 180.97593,
        "sample_std": 69.6059660263,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_G1_G01_073.fcs",
        "MFI_all": 91.8,
        "pct_fluor": 1,
        "MFI": 1665,
        "plate": 1,
        "well": "G1",
        "row": "G",
        "col": 1,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 7",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.1665,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 23.4375,
        "sample_mean": 0.105818,
        "sample_std": 0.0558790022,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_G2_G02_074.fcs",
        "MFI_all": 75.4,
        "pct_fluor": 0.54,
        "MFI": 1046,
        "plate": 1,
        "well": "G2",
        "row": "G",
        "col": 2,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 7",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.056484,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 0.5208333333,
        "sample_mean": 0.105818,
        "sample_std": 0.0558790022,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_G3_G03_075.fcs",
        "MFI_all": 81.6,
        "pct_fluor": 0.67,
        "MFI": 1410,
        "plate": 1,
        "well": "G3",
        "row": "G",
        "col": 3,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 7",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.09447,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 8.3333333333,
        "sample_mean": 0.105818,
        "sample_std": 0.0558790022,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_G4_G04_076.fcs",
        "MFI_all": 243,
        "pct_fluor": 10.1,
        "MFI": 802,
        "plate": 1,
        "well": "G4",
        "row": "G",
        "col": 4,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 15",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.81002,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 51.0416666667,
        "sample_mean": 0.9653933333,
        "sample_std": 0.1453714378,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_G5_G05_077.fcs",
        "MFI_all": 277,
        "pct_fluor": 13.9,
        "MFI": 790,
        "plate": 1,
        "well": "G5",
        "row": "G",
        "col": 5,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 15",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 1.0981,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 55.7291666667,
        "sample_mean": 0.9653933333,
        "sample_std": 0.1453714378,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_G6_G06_078.fcs",
        "MFI_all": 265,
        "pct_fluor": 12.7,
        "MFI": 778,
        "plate": 1,
        "well": "G6",
        "row": "G",
        "col": 6,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 15",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.98806,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 53.6458333333,
        "sample_mean": 0.9653933333,
        "sample_std": 0.1453714378,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_G7_G07_079.fcs",
        "MFI_all": 582,
        "pct_fluor": 48.5,
        "MFI": 1003,
        "plate": 1,
        "well": "G7",
        "row": "G",
        "col": 7,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 23",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 4.86455,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 63.0208333333,
        "sample_mean": 4.6285466667,
        "sample_std": 0.6675625701,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_G8_G08_080.fcs",
        "MFI_all": 494,
        "pct_fluor": 41.4,
        "MFI": 936,
        "plate": 1,
        "well": "G8",
        "row": "G",
        "col": 8,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 23",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 3.87504,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 60.9375,
        "sample_mean": 4.6285466667,
        "sample_std": 0.6675625701,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_G9_G09_081.fcs",
        "MFI_all": 601,
        "pct_fluor": 50.7,
        "MFI": 1015,
        "plate": 1,
        "well": "G9",
        "row": "G",
        "col": 9,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 23",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 5.14605,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 64.0625,
        "sample_mean": 4.6285466667,
        "sample_std": 0.6675625701,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_G10_G10_082.fcs",
        "MFI_all": 77.3,
        "pct_fluor": 0.96,
        "MFI": 2626,
        "plate": 1,
        "well": "G10",
        "row": "G",
        "col": 10,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "Cr-",
        "sample_type": "negative control",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.252096,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 37.5,
        "sample_mean": 0.1438786667,
        "sample_std": 0.0937193781,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_G11_G11_083.fcs",
        "MFI_all": 79,
        "pct_fluor": 0.5,
        "MFI": 1801,
        "plate": 1,
        "well": "G11",
        "row": "G",
        "col": 11,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "Cr-",
        "sample_type": "negative control",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.09005,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 6.7708333333,
        "sample_mean": 0.1438786667,
        "sample_std": 0.0937193781,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_G12_G12_084.fcs",
        "MFI_all": 80.2,
        "pct_fluor": 0.57,
        "MFI": 1570,
        "plate": 1,
        "well": "G12",
        "row": "G",
        "col": 12,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "Cr-",
        "sample_type": "negative control",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.08949,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 6.25,
        "sample_mean": 0.1438786667,
        "sample_std": 0.0937193781,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_H1_H01_085.fcs",
        "MFI_all": 7717,
        "pct_fluor": 96.1,
        "MFI": 8932,
        "plate": 1,
        "well": "H1",
        "row": "H",
        "col": 1,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 8",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 85.83652,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 92.1875,
        "sample_mean": 83.1178366667,
        "sample_std": 9.7136850114,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_H2_H02_086.fcs",
        "MFI_all": 6554,
        "pct_fluor": 96.1,
        "MFI": 7527,
        "plate": 1,
        "well": "H2",
        "row": "H",
        "col": 2,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 8",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 72.33447,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 90.625,
        "sample_mean": 83.1178366667,
        "sample_std": 9.7136850114,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_H3_H03_087.fcs",
        "MFI_all": 8881,
        "pct_fluor": 98.8,
        "MFI": 9229,
        "plate": 1,
        "well": "H3",
        "row": "H",
        "col": 3,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 8",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 91.18252,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 92.7083333333,
        "sample_mean": 83.1178366667,
        "sample_std": 9.7136850114,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_H4_H04_088.fcs",
        "MFI_all": 92.5,
        "pct_fluor": 1.18,
        "MFI": 1463,
        "plate": 1,
        "well": "H4",
        "row": "H",
        "col": 4,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 16",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.172634,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 25,
        "sample_mean": 0.143202,
        "sample_std": 0.0278353833,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_H5_H05_089.fcs",
        "MFI_all": 94.4,
        "pct_fluor": 1,
        "MFI": 1173,
        "plate": 1,
        "well": "H5",
        "row": "H",
        "col": 5,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 16",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.1173,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 13.0208333333,
        "sample_mean": 0.143202,
        "sample_std": 0.0278353833,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_H6_H06_090.fcs",
        "MFI_all": 108,
        "pct_fluor": 1.36,
        "MFI": 1027,
        "plate": 1,
        "well": "H6",
        "row": "H",
        "col": 6,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 16",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.139672,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 19.2708333333,
        "sample_mean": 0.143202,
        "sample_std": 0.0278353833,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_H7_H07_091.fcs",
        "MFI_all": 3151,
        "pct_fluor": 97.4,
        "MFI": 3338,
        "plate": 1,
        "well": "H7",
        "row": "H",
        "col": 7,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 24",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 32.51212,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 83.8541666667,
        "sample_mean": 25.13576,
        "sample_std": 7.2938305427,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_H8_H08_092.fcs",
        "MFI_all": 2437,
        "pct_fluor": 97,
        "MFI": 2574,
        "plate": 1,
        "well": "H8",
        "row": "H",
        "col": 8,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 24",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 24.9678,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 83.3333333333,
        "sample_mean": 25.13576,
        "sample_std": 7.2938305427,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_H9_H09_093.fcs",
        "MFI_all": 1738,
        "pct_fluor": 92.6,
        "MFI": 1936,
        "plate": 1,
        "well": "H9",
        "row": "H",
        "col": 9,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "TUL 24",
        "sample_type": "experiment sample",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 17.92736,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 79.6875,
        "sample_mean": 25.13576,
        "sample_std": 7.2938305427,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_H10_H10_094.fcs",
        "MFI_all": 81.5,
        "pct_fluor": 0.9,
        "MFI": 913,
        "plate": 1,
        "well": "H10",
        "row": "H",
        "col": 10,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "No Abs",
        "sample_type": "fluorescence background",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.08217,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 4.1666666667,
        "sample_mean": 0.0975416667,
        "sample_std": 0.0421651061,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_H11_H11_095.fcs",
        "MFI_all": 77.3,
        "pct_fluor": 0.77,
        "MFI": 847,
        "plate": 1,
        "well": "H11",
        "row": "H",
        "col": 11,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "No Abs",
        "sample_type": "fluorescence background",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.065219,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 1.5625,
        "sample_mean": 0.0975416667,
        "sample_std": 0.0421651061,
        "num_obs": 3
      }, {
        "filename": "Specimen_001_H12_H12_096.fcs",
        "MFI_all": 68,
        "pct_fluor": 0.98,
        "MFI": 1482,
        "plate": 1,
        "well": "H12",
        "row": "H",
        "col": 12,
        "MFI_all_source": "beads/PerCP-Cy5-5-A, SSC-A subset | Geometric Mean (FITC-A)",
        "pct_fluor_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Freq. of Parent",
        "MFI_source": "beads/PerCP-Cy5-5-A, SSC-A subset/FITC-A subset | Geometric Mean (FITC-A)",
        "sample_id": "No Abs",
        "sample_type": "fluorescence background",
        "experiment": "ADCD",
        "sample_dilution": "1:30 (1:10 of 1:3)",
        "cell_donor": null,
        "expt_id": "BMGEXP577",
        "fluor_score": 0.145236,
        "fluor_score_type": "phagocytotic score",
        "fluor_percentile": 20.8333333333,
        "sample_mean": 0.0975416667,
        "sample_std": 0.0421651061,
        "num_obs": 3
      }]

// TODO: properly calc ref lines
  ref_lines: Array<Object> = [
    { 'label': 'negative control', 'value': 0.1438786667 },
    { 'label': 'positive control', 'value': 180.97593 },
    { 'label': 'plate median', 'value': d3.median(this.df2.map(d => d.fluor_score)) }
  ];

  // --- Plot sizing ---
  private element: any;
  private element_dims: any;
  private margin: any = { top: 50, bottom: 50, left: 50, right: 50 };
  private width: number;
  private height: number;
  // private rect_width: number;

  // --- Selectors ---
  private dotplot: any;

  // --- Scales ---
  private x: any;
  private y: any;
  private xAxis: any;
  private yAxis: any;

  private indiv_r: number = 6;
  private avg_width: number = 20;

  private colorScale = d3.scaleSequential(d3Chromatic.interpolateYlGn).domain([0, 200]);


  constructor(){
    // private dataSvc: GetDataService) {
  //   this.dataSvc.getData().subscribe(data => {
  //   console.log('subscribing')
  //   console.log(data)
  //   this.test = data;
  //   console.log(this.test)
  // });
  }

  ngOnInit() {
    // this.df = this.df.sort((a,b) => a.avg - b.avg);
    //
    this.df = d3.nest()
      .key(d => d.sample_id)
      .rollup(function(leaves: any) {
        return {
          'num_obs': leaves.length,
          'sample_mean': d3.mean(leaves, d => d.fluor_score),
          'indivs': leaves.map(d => d.fluor_score),
          'not_control': leaves.map(d => d.sample_type).includes('experiment sample')
        }
      })
      .entries(this.df2)
      .sort((a, b) => a.value.sample_mean - b.value.sample_mean);

    console.log(this.df)

    this.createChart();
  }

  getSVGDims() {
    // Find container; define width/height of svg obj.
    this.element = this.chartContainer.nativeElement;
    this.element_dims = this.element.getBoundingClientRect();
    this.width = this.element.offsetWidth / 2 - this.margin.left - this.margin.right;
    this.height = this.element.offsetHeight - this.margin.top - this.margin.bottom;
  }

  // Data-independent setup
  createChart() {
    this.getSVGDims();

    // this.rect_width = this.width / this.df.length;

    this.x = d3.scaleBand().range([0, this.width]).domain(this.df.map(d => d.key));

    let indiv_max = this.df.map(d => d3.max(d.value.indivs))
    // this.y = d3.scaleLinear().range([this.height, 0]).domain([0, d3.max(indiv_max)])
    this.y = d3.scaleLog().range([this.height, 0]).domain([.05, d3.max(indiv_max)])


    // this.y = d3.scaleLinear().range([this.height, 0]).domain([0, d3.max(this.df.map(d => d.value.indivs.map(g => g)))]);

    // Append SVG
    const svg = d3.select(this.element)
      .append('svg')
      .attr("width", this.width + this.margin.left + this.margin.right)
      .attr("height", this.height + this.margin.top + this.margin.bottom);

    // selectors
    this.dotplot = svg.append("g")
      .attr("id", "dotplot")
      .attr("transform", `translate(${this.margin.left}, ${this.margin.top})`);


    let refs = this.dotplot.selectAll('.ctrl-line')
      .data(this.ref_lines)
      .enter().append('g');

    refs.append('line')
      .attr('class', 'ref-line')
      .classed('ctrl-line', d => d.label != 'plate median')
      .attr("y1", (d, i) => this.y(d.value))
      .attr("y2", (d, i) => this.y(d.value))
      .attr("x1", 0)
      .attr("x2", this.width);

    refs.append('text')
      .attr('class', 'ref-label')
      .classed('right', d => d.label == 'negative control')
      .attr("y", d => this.y(d.value))
      .attr('dy', -10)
      .attr("x", 0)
      .attr('dx', d => d.label == 'negative control' ? this.width : 10)
      .text(d => d.label);

    var grp = this.dotplot.selectAll('.avg')
      .data(this.df).enter().append('g')
    // .enter().append('svg')
    // .attr("width", this.width/3)
    // .attr("height", this.height);

    //       grp.append(g)
    //       .attr('class', 'sm-mult')
    // .attr("transform", (d,i) => `translate(${this.width/3 * i}, 0)`);
    //

    // AXIS

    // this.dotplot.append("g")
    //   .attr("class", "axis axis--x")
    //   .attr("transform", "translate(0," + this.height + ")")
    //   .call(d3.axisBottom(this.x));

    this.dotplot.append("g")
      .attr("class", "axis axis--y")
      .attr("transform", "translate(0," + 0 + ")")
      .call(d3.axisLeft(this.y));







    grp.append('g')
      .attr('class', 'indiv-grp')
      .classed('expt-sample', d => d.value.not_control)
      .attr('transform', (d, i) => 'translate(' + (this.x(d.key) + this.x.bandwidth() / 2) + ',0)')
      .selectAll('.indiv')
      .data(d => d.value.indivs)
      .enter().append("circle")
      .attr("cy", (d, i) => this.y(d))
      .attr("cx", 0)
      .attr("r", this.indiv_r)
      .attr("class", "indiv");

    grp.append('line')
      .attr('class', 'avg-glow')
      .classed('expt-sample', d => d.value.not_control)
      .attr("y1", d => this.y(d.value.sample_mean))
      .attr("y2", d => this.y(d.value.sample_mean))
      .attr("x1", d => this.x(d.key) - this.avg_width + this.x.bandwidth() / 2)
      .attr("x2", d => this.x(d.key) + this.avg_width + this.x.bandwidth() / 2)
      .style("stroke", d => this.colorScale(d.value.sample_mean));

    grp.append('line')
      .attr('class', 'avg')
      .classed('expt-sample', d => d.value.not_control)
      .attr("y1", d => this.y(d.value.sample_mean))
      .attr("y2", d => this.y(d.value.sample_mean))
      .attr("x1", d => this.x(d.key) - this.avg_width + this.x.bandwidth() / 2)
      .attr("x2", d => this.x(d.key) + this.avg_width + this.x.bandwidth() / 2);

    grp.append('text')
      .attr('class', 'ctrl-label')
      .classed('display-off', d => d.value.not_control)
      .attr("y", d => this.y(d.value.sample_mean))
      .attr("dy", -50)
      .attr("x", d => this.x(d.key) + this.x.bandwidth() / 2)
      .text(d => d.key);

    // grp.append('line')
    //     .attr('class', 'divider')
    //     .attr("y1", 0)
    //     .attr("y2", this.height)
    //     .attr("x1", d => this.x(d.key) + this.x.bandwidth())
    //     .attr("x2", d => this.x(d.key) + this.x.bandwidth());
  }

}
